config/routes.rb
PentakillUniversity::Application.routes.draw do  


  post "payment_notifications" => "payment_notifications#create", :as => 'payment_notifications'
  devise_for :users
  get "app/accept/:id" => 'app#accept', :as => 'accept_app'
  get "app/decline/:id" => 'app#decline', :as => 'decline_app'
  post "app/new" => 'app#create', :as => 'create_app'
  get "request/accept/:id" => "request#accept", :as => 'accept_request'
  get "request/decline/:id" => 'request#decline', :as => 'decline_request'
  post "request/new" => "request#create", :as => 'create_request'  
  post "request/notify" => "request#notify", :as => 'paypal_ipn'
  get "user/verify"
  get "user" => 'user#profile'
  get "user/requests"
  get "user/apps"
  get "home/index"
  get "students" => 'user#students'
  get "mentors" => 'user#mentors'
  get "user/:id/request" => 'user#request_mentorship', :as => 'request'
  get "user/:id/apply" => 'user#apply', :as => 'apply'
  get "user/:id" => 'user#show', :as => 'show'
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/payment_notification.rb
require "net/http"
require "uri"

class PaymentNotification < ActiveRecord::Base
  attr_accessible :create, :params, :request_id, :status, :transaction_id
  serialize :params
  after_create :create_relationship

  private

  def create_relationship
  	if status == 'Completed'
  		req = Request.find(request_id)
  		unless req.nil?
        return Rails.logger.info("PaymentNotification #{id} has the wrong price...\r\nmc_gross_1 = #{params[:mc_gross_1]}\r\nprice = #{req.price}") if (params[:mc_gross_1].to_f != req.price.to_f || params[:mc_currency] != 'USD')
  			req.student.relationship =  Relationship.create(:mentor => req.mentor, :price => req.price, :payment_id => self.id)
  			self.request_id = req.student.relationship.id
  			self.save!
  			req.destroy
  		end
  	end
  end
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  protect_from_forgery :except => [:create]
  def create
  	return false unless request_valid?
    PaymentNotification.create!(:params => params, :request_id => params[:item_number1], :status => params[:payment_status], :transaction_id => params[:txn_id] )
    render :nothing => true
  end
  def request_valid?
    uri = URI.parse('https://www.paypal.com/cgi-bin/webscr?cmd=_notify-validate')

    http = Net::HTTP.new(uri.host, uri.port)
    http.open_timeout = 60
    http.read_timeout = 60
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    http.use_ssl = true
    response = http.post(uri.request_uri, request.raw_post,
                         'Content-Length' => "#{request.raw_post.size}",
                         'User-Agent' => "Anujan"
                       ).body

    raise StandardError.new("Faulty paypal result: #{response}") unless ["VERIFIED", "INVALID"].include?(response)
    raise StandardError.new("Invalid IPN: #{response}") unless response == "VERIFIED"

    true
  end
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/views/payment_notifications/_form.html.erb
<%= simple_form_for(@payment_notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :params %>
    <%= f.input :request_id %>
    <%= f.input :status %>
    <%= f.input :transaction_id %>
    <%= f.input :create %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payment_notifications/edit.html.erb
<h1>Editing payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_notification %> |
<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/index.html.erb
<h1>Listing payment_notifications</h1>

<table>
  <tr>
    <th>Params</th>
    <th>Request</th>
    <th>Status</th>
    <th>Transaction</th>
    <th>Create</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_notifications.each do |payment_notification| %>
  <tr>
    <td><%= payment_notification.params %></td>
    <td><%= payment_notification.request_id %></td>
    <td><%= payment_notification.status %></td>
    <td><%= payment_notification.transaction_id %></td>
    <td><%= payment_notification.create %></td>
    <td><%= link_to 'Show', payment_notification %></td>
    <td><%= link_to 'Edit', edit_payment_notification_path(payment_notification) %></td>
    <td><%= link_to 'Destroy', payment_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment notification', new_payment_notification_path %>

app/views/payment_notifications/new.html.erb
<h1>New payment_notification</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Params:</b>
  <%= @payment_notification.params %>
</p>

<p>
  <b>Request:</b>
  <%= @payment_notification.request_id %>
</p>

<p>
  <b>Status:</b>
  <%= @payment_notification.status %>
</p>

<p>
  <b>Transaction:</b>
  <%= @payment_notification.transaction_id %>
</p>

<p>
  <b>Create:</b>
  <%= @payment_notification.create %>
</p>


<%= link_to 'Edit', edit_payment_notification_path(@payment_notification) %> |
<%= link_to 'Back', payment_notifications_path %>