config/routes.rb
PentakillUniversity::Application.routes.draw do  


  post "payment_notifications" => "payment_notifications#create", :as => 'payment_notifications'
  devise_for :users
  get "app/accept/:id" => 'app#accept', :as => 'accept_app'
  get "app/decline/:id" => 'app#decline', :as => 'decline_app'
  post "app/new" => 'app#create', :as => 'create_app'
  get "request/accept/:id" => "request#accept", :as => 'accept_request'
  get "request/decline/:id" => 'request#decline', :as => 'decline_request'
  post "request/new" => "request#create", :as => 'create_request'  
  post "request/notify" => "request#notify", :as => 'paypal_ipn'
  get "user/verify"
  get "user" => 'user#profile'
  get "user/requests"
  get "user/apps"
  get "home/index"
  get "students" => 'user#students'
  get "mentors" => 'user#mentors'
  get "user/:id/request" => 'user#request_mentorship', :as => 'request'
  get "user/:id/apply" => 'user#apply', :as => 'apply'
  get "user/:id" => 'user#show', :as => 'show'
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
require 'json'
require 'socket'

class User < ActiveRecord::Base
	serialize :roles
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	validates :ign, :server, :roles, :presence => true
	validate :summoner_exists
	validate :valid_roles
	attr_accessible :email, :password, :password_confirmation, :remember_me, :ign, :server, :tier, :roles, :type, :verify_code

	def valid_roles
		valid_role_array = ['Top', 'Mid', 'Jungle', 'AD Carry', 'Support']
		roles.each do |role| 
			unless valid_role_array.include?(role)
				self.roles.delete(role)
			end
		end
	end

	def is_mentor?
		return type == 'Mentor'
	end
	
	def summoner_verified?
		return verify_code == 'VERIFIED'
	end
	
	def summoner_verify
		rune_pages = shurima_api(server, 'rune_pages', acctid)
		unless rune_pages
			return false
		else
			rune_pages.each do |page|
				if (page['name'] == verify_code)
					self.verify_code = 'VERIFIED'
					return save
				end
			end
		end
		return false
	end
	
	def summoner_exists
		unless (new_record? || server_changed? || ign_changed?)
			return
		end
		json = self.shurima_api(self.server, 'summoner', self.ign)
		unless !json.nil? || json
			errors.add(:ign, "The summoner name \"#{ign}\" doesn't exist on #{server}")
		else
			self.summonerid = json['summonerId']
			self.acctid = json['acctId']
			self.verify_code = Array.new(10){rand(36).to_s(36)}.join
			eligible_to_mentor
		end
	end
	
	def eligible_to_mentor
		leagues = shurima_api(server, 'leagues', summonerid)
		unless leagues
			errors.add(:ign, "That summoner doesn't seem to meet the requirements to become a mentor. Make sure you're at least in a Platinum League")
			return false
		end
		leagues.each do |league| 
			if (league['queue'] == 'RANKED_SOLO_5x5')
				self.tier = league['tier']
			end
		end
		eligible_tiers = ['PLATINUM', 'DIAMOND', 'CHALLENGER']
		if (type == 'Mentor' && !eligible_tiers.include?(tier))
			errors.add(:type, "Mentors must be at least PLATINUM.")
		end
	end
	
	def shurima_api(serv, method, args)
		host, port = '78.129.218.131', 714
		TCPSocket.open(host, port) do |socket|
			ready = IO.select([socket], [socket], nil, 8)
			unless (ready) 
				return false
			end
			socket.puts serv + "&" + method + "&" + args.to_s
			message = socket.gets.chomp
			if message == '"Unknown error"'
				return false
			end
			return JSON.parse(message)
		end
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :students, :mentors]
  
  def verify
    @user = current_user
    unless (current_user.summoner_verified?)
     result = current_user.summoner_verify
     if (result)
       flash[:notice] = 'Your summoner has now been verified!'
     else
       flash[:error] = 'Your verification was unsuccessful. Please try again.'
     end
    end
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end

  def requests
    @user = current_user
    @requests = @user.requests
  end

  def request_mentorship
    @requester = current_user
    @student = Student.find(params[:id])
    @request = Request.new
  end

  def apps
    @user = current_user
    @app = @user.apps
  end
  
  def apply
    @student = current_user
    @mentor = Mentor.find(params[:id])
    @app = App.new
  end
  
  def students
    @users = Student.where(:verify_code => 'VERIFIED')
  end

  def mentors
    @users = Mentor.where(:verify_code => 'VERIFIED')
  end

  def profile
    @user = current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/apply.html.erb
<%= simple_form_for @app, :url => url_for(action: 'create', controller: 'app'), 
	:html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :message, as: 'text', placeholder: 'Type a short application on who you are and why the mentor should choose you as a student...' %>
  <%= f.hidden_field :mentor, value: @mentor.id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/user/apps.html.erb
<div class="page-header">
  <h1>Applications</h1>
</div>
<% if (current_user.is_mentor?) %>
	<% if (current_user.apps.blank?) %>
		You have no pending apps from students.
	<% else %>
		<table class="table table-striped">
		  <thead>
		    <tr>
		      <th>From</th>
		      <th>Server</th>
		      <th>Role(s)</th>
		      <th>Current Tier</th>
		      <th>Message</th>
		      <th>Accept</th>
		      <th>Decline</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% current_user.apps.each do |app| %>
		      <tr>
		        <td><%= link_to app.student.ign, show_path(app.student) %></td>
		        <td><%= app.student.server %></td>
		        <td><%= app.student.roles.join(', ') %></td>
		        <td><%= app.student.tier %></td>
		        <td><%= app.message %></td>
		        <td><%= link_to "Accept", accept_app_path(app.id), :class => 'btn btn-primary' %></td>
		        <td><%= link_to "Decline", decline_app_path(app.id), :class => 'btn btn-danger' %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	<% end %>
<% else %>
	<% if (current_user.apps.empty?) %>
		You have no pending applications to mentors.
	<% else %>
		<table class="table table-striped">
		  <thead>
		    <tr>
		      <th>To</th>
		      <th>Message</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% current_user.apps.each do |app| %>
		      <tr>
		        <td><%= link_to app.mentor.ign, show_path(app.mentor) %></td>]
		        <td><%= app.message%></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	<% end %>
<% end %>

app/views/user/mentors.html.erb
<%- model_class = Mentor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped datatable">
  <thead>
    <tr>
      <th>IGN</th>
      <th><%= model_class.human_attribute_name(:server) %></th>
      <th><%= model_class.human_attribute_name(:roles) %></th>
      <th><%= model_class.human_attribute_name(:tier) %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.ign, show_path(user) %></td>
      <td><%= user.server %></td>
      <td><%= user.roles.join(', ') %></td>
      <td><%= user.tier %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/user/request.html.erb
<%= simple_form_for @request, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :goal_tier, required: true, priority: ['GOLD'], collection: ['CHALLENGER', 'DIAMOND', 'PLATINUM', 'GOLD', 'SILVER', 'BRONZE'] %>
  <%= f.hidden_field :student, value: @student.id %>
  <%= f.input :goal_division, required: true, priority: ['GOLD'], collection: ['I', 'II', 'III', 'IV', 'V'] %>
  <%= f.input :price %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>
a

app/views/user/request_mentorship.erb
<%= simple_form_for @request, :url => url_for(action: 'create', controller: 'request'), :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :goal_tier, required: true, priority: ['GOLD'], collection: ['CHALLENGER', 'DIAMOND', 'PLATINUM', 'GOLD', 'SILVER', 'BRONZE'] %>
  <%= f.hidden_field :student, value: @student.id %>
  <%= f.input :goal_division, required: true, priority: ['GOLD'], collection: ['I', 'II', 'III', 'IV', 'V'] %>
  <%= f.input :price, :placeholder => '0.00' %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/user/requests.html.erb
<div class="page-header"><h1>Requests</h1></div>
<% unless (current_user.is_mentor?) %>
	<% if (@requests.empty?) %>
		You have no pending requests from mentors.
	<% else %>
		<table class="table table-striped">
		  <thead>
		    <tr>
		      <th>From</th>
		      <th>Server</th>
		      <th>Role(s)</th>
		      <th>Current Tier</th>
		      <th>Goal Tier</th>
		      <th>Goal Division</th>
		      <th>Price</th>
		      <th>Accept</th>
		      <th>Decline</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @requests.each do |req| %>
		      <tr>
		        <td><%= link_to req.student.ign, show_path(req.student) %></td>
		        <td><%= req.student.server %></td>
		        <td><%= req.student.roles.join(', ') %></td>
		        <td><%= req.student.tier %></td>
		        <td><%= req.goal_tier %></td>
		        <td><%= req.goal_division %></td>
		        <td><%= req.price.to_s %></td>
		        <% accept_url = (req.price == 0) ? accept_request_path(req.id) : req.paypal_url(url_for(:controller => "user", :action => "requests", :only_path => false), payment_notifications_url) %>
		        <td><%= link_to "Accept", accept_url, :class => 'btn btn-primary', 'data-no-turbolink' => true  %></td>
		        <td><%= link_to "Decline", decline_request_path(req.id), :class => 'btn btn-danger' %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	<% end %>
<% else %>
	<% if (@requests.empty?) %>
		You have no pending requests to students.
	<% else %>
		<table class="table table-striped">
		  <thead>
		    <tr>
		      <th>To</th>
		      <th>Current Tier</th>
		      <th>Goal Tier</th>
		      <th>Goal Division</th>
		      <th>Price</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @requests.each do |req| %>
		      <tr>
		        <td><%= link_to req.mentor.ign, show_path(req.mentor) %></td>
		        <td><%= req.student.tier %></td>
		        <td><%= req.goal_tier %></td>
		        <td><%= req.goal_division %></td>
		        <td><%= req.price %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	<% end %>
<% end %>

app/views/user/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => @user.ign %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>IGN:</strong></dt>
  <dd><%= @user.ign %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server) %>:</strong></dt>
  <dd><%= @user.server %></dd>
  <dt><strong><%= model_class.human_attribute_name(:roles) %>:</strong></dt>
  <dd><%= @user.roles.join(", ") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tier) %>:</strong></dt>
  <dd><%= @user.tier %></dd>
  <% unless (@user.description.blank?) %>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @user.description %></dd>
  <% end %>
</dl>

<div class="form-actions">
  <% if (@user.type == 'Student' && (!user_signed_in? || current_user.type == 'Mentor')) %>
  	<%= link_to "Request", request_path(@user), :class => 'btn'  %>
  <% elsif (@user.type == 'Mentor' && (!user_signed_in? || current_user.type == 'Student')) %>
  	<%= link_to "Apply", apply_path(@user), :class => 'btn' %>
  <% end %>	
</div>

app/views/user/students.html.erb
<div class="page-header">
  <h1>Students</h1>
</div>
<table class="table table-striped datatable">
  <thead>
    <tr>
      <th>IGN</th>
      <th>Server</th>
      <th>Role(s)</th>
      <th>Tier</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td><%= link_to u.ign, show_path(u) %></td>
        <td><%= u.server %></td>
        <td><%= u.roles.join(', ') %></td>
        <td><%= u.tier %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/verify.html.erb
<h1>User#verify</h1>
<p>Find me in app/views/user/verify.html.erb</p>