config/routes.rb
PentakillUniversity::Application.routes.draw do  


  post "payment_notifications" => "payment_notifications#create", :as => 'payment_notifications'
  devise_for :users
  get "app/accept/:id" => 'app#accept', :as => 'accept_app'
  get "app/decline/:id" => 'app#decline', :as => 'decline_app'
  post "app/new" => 'app#create', :as => 'create_app'
  get "request/accept/:id" => "request#accept", :as => 'accept_request'
  get "request/decline/:id" => 'request#decline', :as => 'decline_request'
  post "request/new" => "request#create", :as => 'create_request'  
  post "request/notify" => "request#notify", :as => 'paypal_ipn'
  get "user/verify"
  get "user" => 'user#profile'
  get "user/requests"
  get "user/apps"
  get "home/index"
  get "students" => 'user#students'
  get "mentors" => 'user#mentors'
  get "user/:id/request" => 'user#request_mentorship', :as => 'request'
  get "user/:id/apply" => 'user#apply', :as => 'apply'
  get "user/:id" => 'user#show', :as => 'show'
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>The Proving Grounds - <%= content_for?(:title) ? yield(:title) : "League of Legends Mentorship Hub" %></title>
  <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->
      <%= stylesheet_link_tag "application", :media => "all" %>
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
      <%= javascript_include_tag "application" %>
            <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41314885-1', 'theprovinggrounds.net');
  ga('send', 'pageview');

</script>
    </head>
    <body>
      <%= nav_bar :fixed => :top, :inverse => true, :brand => "Proving Grounds", :responsive => true do %>
      <%= menu_group do %>
      <%= menu_item "Home", root_path %>
      <%= menu_item "Find Students", students_path %>
      <%= menu_item "Find Mentors", mentors_path %>
      <% end %>
      <%= menu_group :pull => :right do %>
      <%= drop_down (user_signed_in? ? current_user.ign : "Guest") do %>
      <% if user_signed_in? %>
      <% if current_user.type == 'Mentor' %>
      <%= menu_item "My applicants", user_apps_path %>
      <% else %>
      <%= menu_item "My requests", user_requests_path %>
      <% end %>
      <%= menu_item "Settings", edit_user_registration_path %>
      <%= menu_item "Log Out", destroy_user_session_path, :method => :delete %>
      <% else %>
      <%= menu_item "Sign In", new_user_session_path %>
      <%= menu_item "Sign Up", new_user_registration_path %>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <% if (user_signed_in? && !current_user.summoner_verified?) %>
            <div class="alert alert-info">Your summoner isn't verified yet. Please change one of your rune page names to '<%= current_user.verify_code %>' and click the verify button.<br>
              <%= link_to "Verify", user_verify_path, :class => 'btn btn-primary', 'data-no-turbolink' => true %>
            </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
        <footer>
          <div id="footer-wrapper">
           <ul id="footer-container-right">
            <li class="copyright">Copyright © 2013 <%= link_to "Proving Grounds", root_path %>. All Rights Reserved.</li>
            <li class="copyright">Powered by <a href="http://shurima.net">Shurima.NET</a>
            </ul>
          </div>
        </footer>
      </div>
    </body>
    </html>